# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  a: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 100)]
  someVersion: ${{ 0.2.0 }}

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo $(a)
          echo $(someVersion)
          echo $(VERSION)
          export VERSION=0.8.0
