# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  a: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 100)]
  someVersion: ${{ 0.2.0 }}
  major: 1
  major2: 1
  # define b as a counter with the prefix as variable a, and seed as 100.
  minor: $[counter(variables['major'], 1)]
  minor2: $[counter(variables['major2'], 1)]
  Version.MajorMinor: 0.1.0
  Version.Revision: $[counter(variables['Version.MajorMinor'], 0)]

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          echo $(Version.Revision)

